sudo: false
language: c
os:
  - linux
addons:
  postgresql: "9.4"
before_script:
  - git clone https://github.com/nim-lang/Nim.git /cheatfate/Nim
  - cd /cheatfate/Nim
  - git clone --depth 1 https://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - export PATH=$(pwd)/bin:$PATH
  - cd ..
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - cd asyncpg
  - nim c asyncpg
