sudo: false
language: c
os:
  - linux
addons:
  postgresql: "9.4"
before_script:
  - git clone https://github.com/nim-lang/Nim.git
  - cd Nim
  - git clone --depth 1 https://github.com/nim-lang/csources
  - cd csources && sh build.sh
  - cd ..
  - bin/nim c koch
  - ./koch boot -d:release
  - export PATH=$(pwd)/bin:$PATH
  - nim e install_nimble.nims
  - cd ..
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - nim c --path:"." tests/test_types.nim
  - nim c --path:"." tests/test_pool.nim
  - nim c --path:"." tests/test_rows.nim
  - nim c --path:"." tests/test_notifies.nim
  - nim c --path:"." tests/test_utils.nim
  - tests/test_types
  - tests/test_pool
  - tests/test_rows
  - tests/test_notifies
  - tests/test_utils
  - nimble install asyncpg
  - cd tests
  - nim c test_types
  - nim c test_pool
  - nim c test_rows
  - nim c test_notifies
  - nim c test_utils
  - ./test_types
  - ./test_pool
  - ./test_rows
  - ./test_notifies
  - ./test_utils
